### PR TITLE
Feat/treepath

### PR DESCRIPTION
**Pull request by apss-pohl**
Hi @scorninpc ,

this is mainly WIP code but i don't want to get it too far away from master and to avoid future merge conflicts like we recently had. It will not break the build and we can go from there once functions should get implemented.
If you could take a look at the event mask, i don't get why it's not working. Most likely something stupid i am overseeing.

### CODE REVIEW

**Comment by scorninpc** [comment]
Sorry for the question Sven, but i dont got this PR:

You add back GtkTreePath, but does nothing (please, use GtkTreePath always as string, like PHP-GTK2. Always convert it to string before send to PHP landspace), and you add GdkEventMask but does nothing too. And alot comments. Sorry, but what's about?

**Comment by apss-pohl** [comment]
The GtkTreePath: I wanted to implement "get_indices" but then i noticed it is not needed. The idea is to keep that code for the next time when someone eventually want to implement something on "GtkTreePath". But if you don't want to keep it will remove it.
GdkEventMask breaks to build but i don't get why. I comment it out to avoid breaking. I was hoping you spot whats wrong and then it can be added.

**Comment by scorninpc** [comment]
> The GtkTreePath: I wanted to implement "get_indices" but then i noticed it is not needed. The idea is to keep that code for the next time when someone eventually want to implement something on "GtkTreePath". But if you don't want to keep it will remove it.

The GtkTreePath is a freak on Gtk. This is only a struct with a string property. php-gtk 1 and 2, just use it as string. I think you can use the GtkTreeView to do something like `GtkTreeView_::get_indices_path()`

> GdkEventMask breaks to build but i don't get why. I comment it out to avoid breaking. I was hoping you spot whats wrong and then it can be added

Can you give-me some minimal example to use of GdkEventMask?

**Comment by apss-pohl** [comment]
>The GtkTreePath is a freak on Gtk. This is only a struct with a string property. php-gtk 1 and 2, just use it as >string. I think you can use the GtkTreeView to do something like GtkTreeView_::get_indices_path()

Ok i will remove it 

> Can you give-me some minimal example to use of GdkEventMask?

We are using such piece of code:
```PHP
 $window->set_events(GdkEventMask::ALL_EVENTS_MASK);
```
So i added the constants along the lines of others in the codebae, but i always get this complain:

image

So most likely i am overseeing an import but i don't get it.

**Comment by scorninpc** [comment]
Ah! this is a constants only? you dont need to create the class file, just create the constants like https://github.com/scorninpc/php-gtk3/blob/master/main.cpp#L527

**Comment by apss-pohl** [comment]
Did it like this, now the compile doesn`t break, but:
image

Code: 
```php
        Php::Class<Php::Base> gdkeventmask("GdkEventMask");
        gdkeventmask.constant("ALL_EVENTS_MASK", (int)GDK_ALL_EVENTS_MASK);
     ```

**Comment by scorninpc** [comment]
But you add `gdkeventmask` to extension? like this https://github.com/scorninpc/php-gtk3/blob/master/main.cpp#L3731

**Comment by apss-pohl** [comment]
> But you add `gdkeventmask` to extension? like this https://github.com/scorninpc/php-gtk3/blob/master/main.cpp#L3731

This was the missing piece. All set now, thank you Bruno!

**Pull request merged**
