### PR TITLE
Dev/pohl

### PR DESCRIPTION
**Pull request by apss-pohl**

### CODE REVIEW

**Comment by scorninpc** [comment]
Why remove indexes?

If I need to choose use named index or numeric index, i'll choose named index, but why not use two options?

**Comment by apss-pohl** [comment]
This way you get the data duplicated, the array has 4 values which is not what you would expect. If processed further you need to strip out one pair. We can also go with the named index if you prefer i will updated the PR

>and why refactory IFs?
This was my IDE i enabled a code formater. It should not result i a change of functionality,

**Comment by apss-pohl** [comment]
Maybe we can agree in a common code linting? 
Such things improve every codebase.

**Comment by scorninpc** [comment]
> This way you get the data duplicated, the array has 4 values which is not what you would expect. If processed further > you need to strip out one pair. We can also go with the named index if you prefer i will updated the PR

There is no problem to duplicate, its just a pointer, and will not change size or processor time. Using as numeric key, you can use `list($x, $y) = $method()` to retreave. Ans using named, you can just use `$var = $method();`. Is the better world for this two scenarios like PHP-GTK2

> Maybe we can agree in a common code linting?

I think it's to late to think about that now. I think we can focus on uncoded methods, and think about that on next version when will be auto-generated

**Comment by apss-pohl** [comment]
> There is no problem to duplicate, its just a pointer, this will not change size or processor time. Using as numeric key, you > can use list($x, $y) = $method() to retreave. And using named, you can just use $var = $method();. Is the best world for >this two scenarios, like PHP-GTK2 does

So i will change it to the named array. The issue we faced is that the way it is it returns like "X:X:Y:Y" and the code is expecting "X:Y" following the documentation.

> I think it's to late to think about that now. I think we can focus on uncoded methods, and think about that on next 
> version when will be auto-generated

I have no intention to reformat the whole codebase :-) But if you dont mind i would leave the auto format enabled. So if i touch a  file it will receive the formatting. So it will improve over time and it is completely effort less this way. For our app GTK3 will stay for a while. The migration from 2 was, and still is, a big effort and moving on to GTK4 is not realistic in near future for us.

**Comment by scorninpc** [comment]
> So i will change it to the named array. The issue we faced is that the way it is it returns like "X:X:Y:Y" and the code is expecting "X:Y" following the documentation.

Please, leave the two ways. If you change, `list($x, $y) = $method()` will stop work

> I have no intention to reformat the whole codebase :-) But if you dont mind i would leave the auto format enabled. So if i touch a file it will receive the formatting. So it will improve over time and it is completely effort less this way. For our app GTK3 will stay for a while. The migration from 2 was, and still is, a big effort and moving on to GTK4 is not realistic in near future for us.

Look, your code doesn't have a pattern:

- Some one line IFs with { }, some other without; 
- Why a blank comment `//`;
- Some { start in next line, others on the same;

I think this change nothing for now, but this is a pain to me review the PRs

**Comment by apss-pohl** [comment]
> Look, your code doesn't have a pattern
Well its an automated tool so no idea how exactly it is working. But i will turn it off i get your point.

> Please, leave the two ways. If you change, list($x, $y) = $method() will stop work
Ok we will change it in the code then.

**Comment by scorninpc** [comment]
Sorry for that. Thank you for understand me =)

**Pull request closed without merging**
